# Generated by Django 5.1.3 on 2024-11-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_course_description_remove_course_eligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
